version: "2"
services:
  node:
    image: "node:10"
    user: "node"
    working_dir: /home/node/app
    ports:
        - "8081:8081"
    environment:
      - NODE_ENV=development
      - NODE_PORT=8081
      - NODE_WEB_DIR=/docs
    volumes:
      - ./:/home/node/app
    expose:
      - "8081"
    command: "npm start"